// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package query

import ()

type Commission struct {
	ID                 int32  `db:"id"`
	InsuranceID        int64  `db:"insurance_id"`
	Commission         int64  `db:"commission"`
	ProductName        string `db:"product_name"`
	InsuranceAgentName string `db:"insurance_agent_name"`
	ApplicantName      string `db:"applicant_name"`
	InsuredPersonName  string `db:"insured_person_name"`
}
