// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package query

import ()

type Commission struct {
	ID                 int32
	InsuranceID        int64
	Commission         int64
	ProductName        string
	InsuranceAgentName string
	ApplicantName      string
	InsuredPersonName  string
}
